name: lh-bench
channels:
  - conda-forge
dependencies:
  - astroquery
  - jupyter
  - more-itertools
  - memory_profiler
  - numpy
  - python=3.9
  - pandas
  - pip
  - pympler
  - pytest
  - pytest-mock
  - pytest-cov
  - requests
