name: lhorizon
channels:
  - conda-forge
dependencies:
  - jupyter
  - more-itertools
  - numpy
  - python=3.11
  - pandas
  - pip
  - pyerfa
  - pytest
  - pytest-cov
  - pytest-mock
  - requests
  - spiceypy
  - sympy
