name: lhorizon
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - more-itertools
  - numpy
  - python=3.9
  - pandas
  - pip
  - pytest
  - pytest-cov
  - pytest-mock
  - requests
  - spiceypy
  - sympy
