name: publish to pypi
on: workflow_dispatch

jobs:
  build-and-publish:
    name: build and publish
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: lhorizon
          auto-update-conda: false
          python-version: 3.11
          channel-priority: strict
      - name: Set up conda environment
        shell: bash -l {0}
        run: |
          python -m pip install -e .
          conda list
      - name: install build
        run: conda install -n lhorizon build
      - name: build binary & source
        shell: bash -l {0}
        run: |
          conda activate lhorizon
          python -m build --sdist --wheel --outdir dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
