name: doc freshness test
on: workflow_dispatch

jobs:
  build:
    name: ${{ matrix.os }} py${{ matrix.python-version }} ${{ matrix.environment-file }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11", "3.13"]
        environment-file: ["lhorizon/tests/.doc-environment.yml"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: ${{ matrix.environment-file }}
          activate-environment: lh-docs
          auto-update-conda: false
          python-version: ${{ matrix.python-version }}
          channel-priority: strict

      - name: Set up conda environment
        shell: bash -l {0}
        run: conda list

      - name: Run Tests
        shell: bash -l {0}
        run: pytest lhorizon/tests/test_rebuild_docs.py
